/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogo;

/**
 *
 * @author eduar
 */
public class Jogo extends javax.swing.JFrame {

    public boolean jogadorX = true; //jogador 1
    public boolean jogadorO = true; //jogador 2
    public int contadorPosicao;
    public int i,j;
    int op;
    public String linha1, linha2, linha3;
    public String coluna1, coluna2, coluna3;
    public String diagonal1, diagonal2;
    String [][]posicaoVet = new String[3][3];
    
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao1 = new javax.swing.JButton();
        botao2 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botaoReiniciar = new javax.swing.JButton();
        visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");

        botao1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botao2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botao4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botao9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botao7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botaoReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botaoReiniciar.setText("Reiniciar");
        botaoReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoReiniciarActionPerformed(evt);
            }
        });

        visor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        visor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(botaoReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(botaoReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void vezDoJogador(){
        if (jogadorX && jogadorO){
            this.op = 0;
            jogadorX = false;
            jogadorO = true;
            visor.setText("Vez do Jogador O");
        } else if (jogadorX && jogadorO == false){
            this.op = 0;
            jogadorX = false;
            jogadorO = true;
            visor.setText("Vez do Jogador O");
        } else {
            this.op = 1;
            jogadorX = true;
            jogadorO = false;
            visor.setText("Vez do Jogador X");
        }
    }
    
    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao1.setText("X");
            posicaoVet[0][0] = "x";
        } else {
            botao1.setText("O");
            posicaoVet[0][0] = "o";
        }
        botao1.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao2.setText("X");
            posicaoVet[0][1] = "x";
        } else {
            botao2.setText("O");
            posicaoVet[0][1] = "o";
        }
        botao2.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao3.setText("X");
            posicaoVet[0][2] = "x";
        } else {
            botao3.setText("O");
            posicaoVet[0][2] = "o";
        }
        botao3.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao4.setText("X");
            posicaoVet[1][0] = "x";
        } else {
            botao4.setText("O");
            posicaoVet[1][0] = "o";
        }
        botao4.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao5.setText("X");
            posicaoVet[1][1] = "x";
        } else {
            botao5.setText("O");
            posicaoVet[1][1] = "o";
        }
        botao5.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao6.setText("X");
            posicaoVet[1][2] = "x";
        } else {
            botao6.setText("O");
            posicaoVet[1][2] = "o";
        }
        botao6.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao7.setText("X");
            posicaoVet[2][0] = "x";
        } else {
            botao7.setText("O");
            posicaoVet[2][0] = "o";
        }
        botao7.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao8.setText("X");
            posicaoVet[2][1] = "x";
        } else {
            botao8.setText("O");
            posicaoVet[2][1] = "o";
        }
        botao8.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        // TODO add your handling code here:
        vezDoJogador();
        if (op == 0){
            botao9.setText("X");
            posicaoVet[2][2] = "x";
        } else {
            botao9.setText("O");
            posicaoVet[2][2] = "o";
        }
        botao9.setEnabled(false);
        verificarPosicao();
        verificarVencedor();
    }//GEN-LAST:event_botao9ActionPerformed

    private void botaoReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoReiniciarActionPerformed
        // TODO add your handling code here:
        botao1.setText("");
        botao1.setEnabled(true);
        botao2.setText("");
        botao2.setEnabled(true);
        botao3.setText("");
        botao3.setEnabled(true);
        botao4.setText("");
        botao4.setEnabled(true);
        botao5.setText("");
        botao5.setEnabled(true);
        botao6.setText("");
        botao6.setEnabled(true);
        botao7.setText("");
        botao7.setEnabled(true);
        botao8.setText("");
        botao8.setEnabled(true);
        botao9.setText("");
        botao9.setEnabled(true);
        resetarJogo();
        visor.setText("");
        jogadorX = true;
        jogadorO = true;
    }//GEN-LAST:event_botaoReiniciarActionPerformed

    public void resetarJogo(){
        for(i = 0; i < 3; i++){
            for(j = 0; j < 3; j++){
                posicaoVet[i][j] = "";
            }
        }
    }
    
    public void verificarVencedor(){
        linha1 = posicaoVet[0][0] + posicaoVet[0][1] + posicaoVet[0][2];
        linha2 = posicaoVet[1][0] + posicaoVet[1][1] + posicaoVet[1][2];
        linha3 = posicaoVet[2][0] + posicaoVet[2][1] + posicaoVet[2][2];
        coluna1 = posicaoVet[0][0] + posicaoVet[1][0] + posicaoVet[2][0];
        coluna2 = posicaoVet[0][1] + posicaoVet[1][1] + posicaoVet[1][2];
        coluna3 = posicaoVet[2][0] + posicaoVet[2][1] + posicaoVet[2][2];
        diagonal1 = posicaoVet[0][0] + posicaoVet[1][1] + posicaoVet[2][2];
        diagonal2 = posicaoVet[0][2] + posicaoVet[1][1] + posicaoVet[2][0];
        
        if (linha1.equals("xxx") || linha2.equals("xxx") || linha3.equals("xxx") ||
            coluna1.equals("xxx") || coluna2.equals("xxx") || coluna3.equals("xxx") ||
            diagonal1.equals("xxx") || diagonal2.equals("xxx")){
                visor.setText("O vencedor é o X");
                desativarBotoes();
        } else if (linha1.equals("ooo") || linha2.equals("ooo") || linha3.equals("ooo") ||
            coluna1.equals("ooo") || coluna2.equals("ooo") || coluna3.equals("ooo") ||
            diagonal1.equals("ooo") || diagonal2.equals("ooo")){
                visor.setText("O vencedor é o O");
                desativarBotoes();
        } else if (contadorPosicao == 9) {
            visor.setText("Nao ha vencedor");
        }
    }
    
    public void verificarPosicao(){
        contadorPosicao = 0;
        for(i = 0; i < 3; i++){
            for(j = 0; j < 3; j++){
                if (posicaoVet[i][j] == "x" || posicaoVet[i][j] == "o"){
                    contadorPosicao+=1;
                }
            }
        }
    }
    
    public void desativarBotoes(){
        botao1.setEnabled(false);
        botao2.setEnabled(false);
        botao3.setEnabled(false);
        botao4.setEnabled(false);
        botao5.setEnabled(false);
        botao6.setEnabled(false);
        botao7.setEnabled(false);
        botao8.setEnabled(false);
        botao9.setEnabled(false);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoReiniciar;
    private javax.swing.JTextField visor;
    // End of variables declaration//GEN-END:variables
}
